import { createHash } from 'node:crypto';
import type { EvaluationStatus, Finding, InspectionRequest, OverallInspectionResult } from '../../domain/types.js';
import { evaluateInspection as evaluateBase } from './evaluator.js';
import { SOURCES } from '../legal/sources.js';
import { secondScheduleAppliesOn } from '../legal/second-schedule.js';
import { tableIIFinding } from './table-ii-evaluator.js';
import { unitSalePriceFinding } from './unit-sale-price-evaluator.js';
import { ecommerceCountryOriginFinding } from './ecommerce-country-origin-evaluator.js';
import { rule6DeclarationsFindings } from './rule-6-declarations-evaluator.js';
import { rules14To17Findings } from './rules-14-17-evaluator.js';
import { rule31AdvertisementFindings } from './rule-31-advertisement-evaluator.js';
import { rules32To34Findings } from './rules-32-34-evaluator.js';
import { sixthScheduleFindings } from './sixth-schedule-evaluator.js';
import { rules29To30Findings } from './rules-29-30-evaluator.js';
import { unverifiedRuleFindings } from '../legal/rule-review-status.js';
import { rule20Findings } from './rule-20-evaluator.js';

const SOURCE = SOURCES.PRINCIPAL_2011;
function path(input: unknown, key: string): unknown { return key.split('.').reduce<unknown>((v, p) => v != null && typeof v === 'object' ? (v as Record<string, unknown>)[p] : undefined, input); }
function evidenceValue(r: InspectionRequest, field: string): unknown { const direct = path(r, field); if (direct !== undefined) return direct; const e = r.evidence.find(x => x.field === field || x.field === field.replace(/^declarations\./, '')); return e?.normalizedValue ?? e?.rawValue; }
function currencyNumber(v: unknown): number | undefined { if (typeof v === 'number' && Number.isFinite(v)) return v; if (typeof v !== 'string') return undefined; const n = Number(v.replace(/₹|rs\.?/gi, '').trim()); return Number.isFinite(n) ? n : undefined; }
function finding(id: string, code: string, number: string, status: EvaluationStatus, field: string, message: string, reason?: string, missing?: string[]): Finding { return { findingId: id, ruleId: code, ruleCode: code, ruleNumber: number, ruleVersion: 1, status, field, message, violationReason: reason, missingEvidence: missing, legalReferences: [SOURCE], severity: status === 'VIOLATION' ? 'CRITICAL' : 'HIGH', requiresLegalReview: false }; }
const THIRD_SCHEDULE = ['soap', 'lotion', 'cream', 'camphor'];
const QUANTITY_AMBIGUITY_PATTERNS = [/\bapproximately\b/i, /\bapprox\.?\b/i, /\babout\b/i, /\baround\b/i, /\broughly\b/i, /\bnearly\b/i, /\bmore\s+or\s+less\b/i, /\bup\s+to\b/i];
const COUNT_WORDS = ['number', 'unit', 'piece', 'pieces', 'pair', 'pairs', 'set', 'sets'];

function rule11(r: InspectionRequest): Finding[] { const out: Finding[] = []; const p = r.packaging; if (!p) return out; if (p.netQuantityExcludesPackaging === false) out.push(finding('PCR-R11-NET', 'PCR-R11-1', '11(1)', 'VIOLATION', 'packaging.netQuantityExcludesPackaging', 'The measured net quantity is not confirmed to exclude wrappers or other packaging material.', 'Rule 11(1) requires net quantity to exclude wrappers/materials other than the commodity.')); else if (p.netQuantityExcludesPackaging === undefined && r.measurements) out.push(finding('PCR-R11-NET-UNVERIFIED', 'PCR-R11-1', '11(1)', 'UNABLE_TO_VERIFY', 'packaging.netQuantityExcludesPackaging', 'Packaging exclusion was not established by the supplied evidence.', undefined, ['packaging.netQuantityExcludesPackaging'])); const variation = p.environmentalVariation; const qualification = (p.quantityQualification ?? '').trim().toLowerCase(); const whenPacked = qualification === 'when packed'; if (variation === 'NONE' || variation === 'NEGLIGIBLE') { if (whenPacked) out.push(finding('PCR-R11-QUALIFICATION', 'PCR-R11-2', '11(2)-(3)', 'VIOLATION', 'packaging.quantityQualification', 'The declaration uses “when packed” although the supplied variation classification does not permit that qualification.', 'Rule 11(2)-(3) does not permit the “when packed” qualification for commodities with no or negligible environmental variation.')); else if (variation === 'NEGLIGIBLE' && !r.measurements) out.push(finding('PCR-R11-VARIATION-MEASURE', 'PCR-R11-3', '11(3)', 'UNABLE_TO_VERIFY', 'measurements', 'Negligible environmental variation was identified, but no quantity measurement was supplied to establish that the consumer receives not less than the declared quantity.', undefined, ['measurements'])); } else if (variation === 'SIGNIFICANT' && whenPacked) { const commodity = r.productMetadata.commodityCategory.toLowerCase(); if (!THIRD_SCHEDULE.some(x => commodity.includes(x))) out.push(finding('PCR-R11-THIRD-SCHEDULE', 'PCR-R11-4', '11(4)', 'VIOLATION', 'packaging.quantityQualification', '“When packed” is used for a commodity not identified in the configured Third Schedule set.', 'Rule 11(4) permits the qualification only for commodities specified in the Third Schedule.')); else out.push(finding('PCR-R11-THIRD-SCHEDULE-PASS', 'PCR-R11-4', '11(4)', 'PASS', 'packaging.quantityQualification', 'The “when packed” qualification is supported by the supplied significant-variation and Third Schedule evidence.')); } else if (variation === 'UNKNOWN' || variation === undefined) { if (whenPacked || r.measurements) out.push(finding('PCR-R11-VARIATION', 'PCR-R11-VARIATION', '11', 'UNABLE_TO_VERIFY', 'packaging.environmentalVariation', 'Environmental variation classification is required to determine the legally applicable Rule 11 quantity declaration treatment.', undefined, ['packaging.environmentalVariation'])); } return out; }
function rule12_6(r: InspectionRequest): Finding[] { const raw = evidenceValue(r, 'declarations.quantityText') ?? evidenceValue(r, 'quantityDeclarationText') ?? evidenceValue(r, 'declarations.netQuantityText'); if (raw === undefined || raw === null || String(raw).trim() === '') return []; const text = String(raw).trim(); if (QUANTITY_AMBIGUITY_PATTERNS.some(p => p.test(text))) return [finding('PCR-R12-6-VIOLATION', 'PCR-R12-6', '12(6)', 'VIOLATION', 'declarations.quantityText', `The quantity declaration contains an expression that can create an exaggerated, misleading or inadequate expression as to quantity: “${text}”.`, 'Rule 12(6) prohibits words or expressions of any sort that tend to create or are likely to create an exaggerated, misleading or inadequate expression as to the quantity of the commodity contained in the package.')]; return [finding('PCR-R12-6-PASS', 'PCR-R12-6', '12(6)', 'PASS', 'declarations.quantityText', 'No configured misleading quantity-expression pattern was detected in the supplied quantity declaration.')]; }
function rule13_5_ii(r: InspectionRequest): Finding[] { const soldByNumber = evidenceValue(r, 'productMetadata.soldByNumber') ?? evidenceValue(r, 'soldByNumber') ?? evidenceValue(r, 'declarations.soldByNumber'); if (soldByNumber !== true && String(soldByNumber).toLowerCase() !== 'true') return []; const raw = evidenceValue(r, 'declarations.quantityText') ?? evidenceValue(r, 'quantityDeclarationText') ?? evidenceValue(r, 'declarations.netQuantityText'); if (raw === undefined || raw === null || String(raw).trim() === '') return [finding('PCR-R13-5-II-UNVERIFIED', 'PCR-R13-5-II', '13(5)(ii)', 'UNABLE_TO_VERIFY', 'declarations.quantityText', 'The package is identified as an item sold by number, but the quantity declaration text was not supplied.', undefined, ['declarations.quantityText'])]; const text = String(raw).trim(); const hasNumber = /\d/.test(text); const hasCountWord = COUNT_WORDS.some(word => new RegExp('\\b' + word + '\\b', 'i').test(text)); if (!hasNumber) return [finding('PCR-R13-5-II-VIOLATION', 'PCR-R13-5-II', '13(5)(ii)', 'VIOLATION', 'declarations.quantityText', `The quantity declaration “${text}” does not state a numerical quantity for an item sold by number.`, 'Rule 13(5)(ii) requires the number, unit, piece, pair, set or another word representing the quantity to be mentioned.')]; if (!hasCountWord) return [finding('PCR-R13-5-II-UNVERIFIED', 'PCR-R13-5-II', '13(5)(ii)', 'UNABLE_TO_VERIFY', 'declarations.quantityText', `The numerical declaration “${text}” does not contain a recognised number/unit/piece/pair/set quantity word; another legally valid quantity word may be present and requires verification.`, undefined, ['declarations.quantityUnitWord']); return [finding('PCR-R13-5-II-PASS', 'PCR-R13-5-II', '13(5)(ii)', 'PASS', 'declarations.quantityText', 'The item is sold by number and the quantity declaration contains a numerical quantity with a recognised number/unit/piece/pair/set word.')]; }
function rule18(r: InspectionRequest): Finding[] { const out: Finding[] = []; if (r.transaction === undefined && evidenceValue(r, 'transaction.salePrice') === undefined) return out; const sale = currencyNumber(evidenceValue(r, 'transaction.salePrice')); const mrp = currencyNumber(evidenceValue(r, 'declarations.retailSalePrice') ?? evidenceValue(r, 'transaction.mrp')); if (sale === undefined) out.push(finding('PCR-R18-2-UNVERIFIED', 'PCR-R18-2', '18(2)', 'UNABLE_TO_VERIFY', 'transaction.salePrice', 'The actual sale price was not supplied, so compliance with the MRP ceiling cannot be verified.', undefined, ['transaction.salePrice'])); else if (mrp === undefined) out.push(finding('PCR-R18-2-MRP-UNVERIFIED', 'PCR-R18-2', '18(2)', 'UNABLE_TO_VERIFY', 'declarations.retailSalePrice', 'The applicable retail sale price declaration was not supplied, so the sale-price ceiling cannot be verified.', undefined, ['declarations.retailSalePrice'])); else if (sale > mrp) out.push(finding('PCR-R18-2-VIOLATION', 'PCR-R18-2', '18(2)', 'VIOLATION', 'transaction.salePrice', `The sale price (${sale}) exceeds the declared retail sale price (${mrp}).`, 'Rule 18(2) prohibits sale of a packaged commodity above its retail sale price.')); else out.push(finding('PCR-R18-2-PASS', 'PCR-R18-2', '18(2)', 'PASS', 'transaction.salePrice', `The sale price (${sale}) does not exceed the declared retail sale price (${mrp}).`)); const conflict = r.transaction?.identicalPackagePriceConflict; if (conflict === true) out.push(finding('PCR-R18-2A-VIOLATION', 'PCR-R18-2A', '18(2A)', 'VIOLATION', 'transaction.identicalPackagePriceConflict', 'Identical pre-packaged commodities were supplied with different MRPs through the inspected pricing evidence.', 'Rule 18(2A) prohibits declaring different MRPs on identical pre-packaged commodities through restrictive or unfair trade practices, subject to the rule and applicable law.')); else if (conflict === false) out.push(finding('PCR-R18-2A-PASS', 'PCR-R18-2A', '18(2A)', 'PASS', 'transaction.identicalPackagePriceConflict', 'No conflicting MRP evidence was identified for the identical packages in the supplied inspection evidence.')); else out.push(finding('PCR-R18-2A-UNVERIFIED', 'PCR-R18-2A', '18(2A)', 'UNABLE_TO_VERIFY', 'transaction.identicalPackagePriceConflict', 'No evidence was supplied to determine whether identical pre-packaged commodities carry different MRPs.', undefined, ['transaction.identicalPackagePriceConflict'])); return out; }
function canonical(v: unknown): string { if (v === null || typeof v !== 'object') return JSON.stringify(v); if (Array.isArray(v)) return `[${v.map(canonical).join(',')}]`; const o = v as Record<string, unknown>; return `{${Object.keys(o).sort().map(k => `${JSON.stringify(k)}:${canonical(o[k])}`).join(',')}}`; }
export function evaluateInspectionComplete(r: InspectionRequest): OverallInspectionResult { const base = evaluateBase(r); const historicalFindings = secondScheduleAppliesOn(r.inspectionDate) ? base.findings : base.findings.filter(f => f.ruleCode !== 'PCR-R5-SCHEDULE-II'); const tableII = tableIIFinding(r); const unitSalePrice = unitSalePriceFinding(r); const ecommerceCountryOrigin = ecommerceCountryOriginFinding(r); const rule6 = rule6DeclarationsFindings(r); const rules14To17 = rules14To17Findings(r); const rule31 = rule31AdvertisementFindings(r); const rules32To34 = rules32To34Findings(r); const sixthSchedule = sixthScheduleFindings(r); const rules29To30 = rules29To30Findings(r); const legalReview = unverifiedRuleFindings(r); const rule20 = rule20Findings(r); const added = [...rule6, ...rule11(r), ...rule12_6(r), ...rule13_5_ii(r), ...rule18(r), ...rules14To17, ...rule31, ...rules29To30, ...rule20, ...rules32To34, ...sixthSchedule, ...legalReview, ...(tableII ? [tableII] : []), ...(unitSalePrice ? [unitSalePrice] : []), ...(ecommerceCountryOrigin ? [ecommerceCountryOrigin] : [])]; const findings = [...historicalFindings, ...added]; const summary = { totalRulesEvaluated: findings.length, passed: findings.filter(f => f.status === 'PASS').length, violations: findings.filter(f => f.status === 'VIOLATION').length, unableToVerify: findings.filter(f => f.status === 'UNABLE_TO_VERIFY').length, notApplicable: findings.filter(f => f.status === 'NOT_APPLICABLE').length }; const overallStatus: EvaluationStatus = summary.violations > 0 ? 'VIOLATION' : summary.unableToVerify > 0 ? 'UNABLE_TO_VERIFY' : summary.passed > 0 ? 'PASS' : 'NOT_APPLICABLE'; const result = { ...base, overallStatus, summary, findings }; return { ...result, auditHash: createHash('sha256').update(canonical(result)).digest('hex') }; }
