import express from "express";
import { authenticate } from "../middleware/auth.js";
import prisma from "../lib/prisma.js";
const router=express.Router();router.use(authenticate);
const SOURCE_TYPES=new Set(["OFFLINE","ECOMMERCE"]);const normalizeSource=v=>{const s=String(v||"OFFLINE").toUpperCase();return SOURCE_TYPES.has(s)?s:null};const slugify=v=>String(v).normalize("NFKD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"category";function depthOf(c){let d=1,p=c;while(p?.parent){d++;p=p.parent}return d}function tree(cs){const map=new Map();cs.forEach(c=>{const k=c.parentId||"ROOT";if(!map.has(k))map.set(k,[]);map.get(k).push({...c,children:[]})});const build=k=>(map.get(k)||[]).map(c=>({...c,children:build(c.id)}));return build("ROOT")}const visible=(uid,id)=>({id,OR:[{isSystem:true},{ownerId:uid}]});const categoryProductSelect={id:true,productName:true,brandName:true,netQuantity:true,unit:true,mrp:true,complianceStatus:true,sourceType:true,createdAt:true,inspections:{select:{inspectedAt:true,shop:{select:{id:true,name:true}}},orderBy:{inspectedAt:"desc"},take:1}};
router.get("/",async(req,res)=>{try{const source=req.query.sourceType?normalizeSource(req.query.sourceType):null;if(req.query.sourceType&&!source)return res.status(400).json({error:"sourceType must be OFFLINE or ECOMMERCE"});res.json(await prisma.category.findMany({where:{parentId:null,OR:[{isSystem:true},{ownerId:req.user.id}],...(source?{sourceType:source}:{})},include:{children:{orderBy:{name:"asc"}}},orderBy:{name:"asc"}}));}catch(e){res.status(500).json({error:e.message})}});
router.get("/tree/all",async(req,res)=>{try{const source=req.query.sourceType?normalizeSource(req.query.sourceType):null;const cs=await prisma.category.findMany({where:{OR:[{isSystem:true},{ownerId:req.user.id}],...(source?{sourceType:source}:{})},orderBy:{name:"asc"}});res.json(tree(cs));}catch(e){res.status(500).json({error:e.message})}});
router.get("/id/:id",async(req,res)=>{try{const c=await prisma.category.findFirst({where:visible(req.user.id,req.params.id),select:{id:true,name:true,slug:true,parentId:true,isSystem:true,sourceType:true,ownerId:true,isFinalProductType:true,createdAt:true,updatedAt:true,parent:{select:{id:true,name:true,sourceType:true,isSystem:true,ownerId:true,parent:{select:{id:true,name:true,sourceType:true,isSystem:true,ownerId:true,parent:{select:{id:true,name:true,sourceType:true,isSystem:true,ownerId:true}}}}}},children:{orderBy:{name:"asc"}},products:{where:{ownerId:req.user.id},select:categoryProductSelect,orderBy:{createdAt:"desc"},take:500}}});if(!c)return res.status(404).json({error:"Category not found"});res.json(c);}catch(e){res.status(500).json({error:e.message})}});
async function createCategory(req,res,global=false){try{const name=String(req.body.name||"").trim(),parentId=req.body.parentId||null,isFinal=Boolean(req.body.isFinal);if(!name)return res.status(400).json({error:"Category name is required"});if(global&&req.user.role!=="ADMIN")return res.status(403).json({error:"Only admins can create global categories"});let parent=null,sourceType=normalizeSource(req.body.sourceType)||"OFFLINE",depth=1;if(parentId){parent=await prisma.category.findFirst({where:global?{id:parentId,isSystem:true}:visible(req.user.id,parentId),include:{parent:{include:{parent:{include:{parent:true}}}}}});if(!parent)return res.status(404).json({error:"Parent category not found"});if(parent.isFinalProductType)return res.status(400).json({error:"Final categories cannot contain subcategories"});if(parent.isSystem)sourceType=parent.sourceType;else if(parent.sourceType!==sourceType)return res.status(400).json({error:"A category must use the same source type as its parent"});depth=depthOf(parent)+1;if(depth>4)return res.status(400).json({error:"Maximum category hierarchy is four levels"});}const data={name,slug:`${slugify(req.body.slug||name)}-${sourceType.toLowerCase()}-${global?"global":req.user.id.slice(-8)}`,sourceType,isFinalProductType:depth===4||isFinal,isSystem:global};if(parentId)data.parent={connect:{id:parentId}};if(!global)data.owner={connect:{id:req.user.id}};res.status(201).json(await prisma.category.create({data}));}catch(e){res.status(e.code==="P2002"?409:500).json({error:e.code==="P2002"?"A category with this name already exists":"Failed to create category"})}}
router.post("/",(req,res)=>createCategory(req,res,false));router.post("/global",(req,res)=>createCategory(req,res,true));
router.patch("/:id/final",async(req,res)=>{try{const c=await prisma.category.findFirst({where:visible(req.user.id,req.params.id),include:{children:true}});if(!c)return res.status(404).json({error:"Category not found"});if(c.isSystem&&req.user.role!=="ADMIN")return res.status(403).json({error:"Admin required"});if(req.body.isFinal&&c.children.length)return res.status(400).json({error:"A category with subcategories cannot be final"});res.json(await prisma.category.update({where:{id:c.id},data:{isFinalProductType:req.body.isFinal!==false}}));}catch(e){res.status(500).json({error:e.message})}});
router.delete("/:id",async(req,res)=>{try{const c=await prisma.category.findFirst({where:req.user.role==="ADMIN"?{id:req.params.id}:visible(req.user.id,req.params.id)});if(!c)return res.status(404).json({error:"Category not found"});if(c.isSystem&&req.user.role!=="ADMIN")return res.status(403).json({error:"Global categories cannot be deleted by users"});const ids=[c.id];const all=await prisma.category.findMany({where:req.user.role==="ADMIN"?{}:{OR:[{isSystem:true},{ownerId:req.user.id}]},select:{id:true,parentId:true}});for(let i=0;i<ids.length;i++)for(const x of all)if(x.parentId===ids[i]&&!ids.includes(x.id))ids.push(x.id);const products=await prisma.product.count({where:{categoryId:{in:ids}}});const source=c.sourceType||"OFFLINE";let fallback=await prisma.category.findFirst({where:{isSystem:true,parentId:null,sourceType:source,name:`Uncategorized (${source==="ECOMMERCE"?"E-commerce":"Offline"})`}});if(!fallback)fallback=await prisma.category.create({data:{name:`Uncategorized (${source==="ECOMMERCE"?"E-commerce":"Offline"})`,slug:`uncategorized-${source.toLowerCase()}-${Date.now()}`,sourceType:source,isSystem:true,isFinalProductType:true}});await prisma.$transaction(async tx=>{await tx.product.updateMany({where:{categoryId:{in:ids}},data:{categoryId:fallback.id}});for(const x of [...ids].reverse())await tx.category.delete({where:{id:x}})});res.json({message:`Category deleted. ${products} product(s) moved to ${fallback.name}.`});}catch(e){res.status(500).json({error:e.message})}});
export default router;
