import express from "express";
import sharp from "sharp";
import { authenticate } from "../middleware/auth.js";
const router=express.Router();router.use(authenticate);
function isPrivateHost(hostname){const h=String(hostname||"").toLowerCase();return h==="localhost"||h.endsWith(".local")||h==="::1"||h==="0.0.0.0"||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[0-1])\./.test(h);}
function isNative(t){return ["image/jpeg","image/png","image/webp"].includes(String(t||"").split(";")[0].trim().toLowerCase());}
async function normalizeImage(buffer,contentType){const t=String(contentType||"").split(";")[0].trim().toLowerCase();if(isNative(t))return{buffer,mediaType:t,extension:t==="image/png"?"png":t==="image/webp"?"webp":"jpg"};const converted=await sharp(buffer,{failOn:"none"}).rotate().jpeg({quality:90,mozjpeg:true}).toBuffer();return{buffer:converted,mediaType:"image/jpeg",extension:"jpg"};}
router.post("/images",async(req,res)=>{try{const imageUrls=Array.isArray(req.body?.imageUrls)?req.body.imageUrls.slice(0,6):[];if(!imageUrls.length)return res.status(400).json({error:"At least one public product image URL is required."});const fd=new FormData();let added=0;const skipped=[];for(const raw of imageUrls){try{const u=new URL(String(raw||""));if(!["http:","https:"].includes(u.protocol)||isPrivateHost(u.hostname)){skipped.push("private-or-invalid-url");continue;}const r=await fetch(u.href,{headers:{"user-agent":"PARAKH Compliance Inspection/1.0",accept:"image/avif,image/webp,image/jpeg,image/png,image/*,*/*;q=0.8"},signal:AbortSignal.timeout(10000)});if(!r.ok){skipped.push(`http-${r.status}`);continue;}const type=r.headers.get("content-type")||"application/octet-stream",buffer=Buffer.from(await r.arrayBuffer());if(!buffer.length||buffer.length>16*1024*1024){skipped.push("empty-or-too-large");continue;}const normalized=await normalizeImage(buffer,type);fd.append("images",new Blob([normalized.buffer],{type:normalized.mediaType}),`ecommerce-${added+1}.${normalized.extension}`);added++;}catch(e){skipped.push(e?.message||"download-or-conversion-failed");}}if(!added)return res.status(422).json({error:"No usable public product images were available for OCR.",skipped});const baseUrl=String(process.env.INTERNAL_BASE_URL||`http://127.0.0.1:${Number(process.env.PORT||5000)}`).replace(/\/$/,"");const r=await fetch(`${baseUrl}/api/ocr/analyze`,{method:"POST",body:fd,headers:req.headers.authorization?{authorization:req.headers.authorization}:{},signal:AbortSignal.timeout(45000)});const data=await r.json().catch(()=>({}));if(!r.ok)return res.status(r.status).json({error:data?.error?.message||data?.error||"Shared OCR engine failed."});res.json({result:data.result||null,provider:data.provider||"local-rules",model:data.model||"local declaration mapper",semantic:data.semantic||data.result?.semantic||null,detectionProvider:data.detectionProvider||"paddleocr",detectionProviders:data.detectionProviders||["paddleocr"],fallbackReason:data.fallbackReason||null,engine:"parakh-fast-ocr",imageCount:added,skipped});}catch(e){res.status(e?.name==="TimeoutError"?504:502).json({error:e?.message||"E-commerce image OCR failed."});}});
export default router;
