import express from "express";
import prisma from "../lib/prisma.js";
import { authenticate } from "../middleware/auth.js";
const router=express.Router();router.use(authenticate);
const visibility=req=>req.user.role==="ADMIN"?{}:{ownerId:req.user.id};const num=v=>{const n=Number.parseFloat(String(v??"").replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:null};
function verifyProduct({brandName,productName,netQuantity,unit,mrp}){const missing=[];if(!brandName?.trim())missing.push("manufacturer/brand information");if(!productName?.trim())missing.push("product name");if(!netQuantity?.trim())missing.push("net quantity");if(!unit?.trim())missing.push("quantity unit");if(mrp==null||mrp===""||Number.isNaN(Number(mrp)))missing.push("MRP");return missing.length?{status:"VIOLATION",reason:`Missing declaration(s) requiring inspection: ${missing.join(", ")}.`}:{status:"OKAY",reason:"Automated OCR and Rules Engine assessment completed; final legal verification remains with the inspector."};}
const baseSelect={id:true,productName:true,brandName:true,netQuantity:true,unit:true,mrp:true,complianceStatus:true,createdAt:true,sourceType:true,sourceUrl:true,sourceWebsiteName:true,category:{select:{id:true,name:true}},inspections:{select:{inspectedAt:true,shop:{select:{id:true,name:true,sourceType:true}}},orderBy:{inspectedAt:"desc"},take:1}};
router.get("/history",async(req,res)=>{try{const q=String(req.query.query||"").trim(),source=String(req.query.sourceType||"ALL").toUpperCase(),status=String(req.query.status||"ALL");const data=await prisma.product.findMany({where:{...visibility(req),...(source!=="ALL"?{sourceType:source}:{})...(status!=="ALL"?{complianceStatus:status}:{}),...(q?{OR:[{productName:{contains:q,mode:"insensitive"}},{brandName:{contains:q,mode:"insensitive"}},{barcode:{contains:q,mode:"insensitive"}}]}:{})},select:{...baseSelect,barcode:true,violationReason:true,owner:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:"desc"},take:500});res.json(data);}catch(e){res.status(500).json({error:e.message})}});
router.get("/",async(req,res)=>{try{const{categoryId,status="ALL",sourceType="ALL",brandName,productName,unit,minQuantity,maxQuantity,shopName,minMrp,maxMrp}=req.query;const source=String(sourceType).toUpperCase();const data=await prisma.product.findMany({where:{...visibility(req),...(categoryId?{categoryId}:{}),...(status!=="ALL"?{complianceStatus:status}:{}),...(source!=="ALL"?{sourceType:source}:{}),...(brandName?{brandName:{contains:brandName,mode:"insensitive"}}:{}),...(productName?{productName:{contains:productName,mode:"insensitive"}}:{}),...(unit?{unit:{equals:unit,mode:"insensitive"}}:{}),...(minMrp||maxMrp?{mrp:{...(minMrp?{gte:Number(minMrp)}:{}),...(maxMrp?{lte:Number(maxMrp)}:{})}}:{}),...(shopName?{inspections:{some:{shop:{name:{contains:shopName,mode:"insensitive"}}}}}: {})},select:baseSelect,orderBy:{createdAt:"desc"},take:500});const minQ=minQuantity?Number(minQuantity):null,maxQ=maxQuantity?Number(maxQuantity):null;res.json(data.filter(p=>{const q=num(p.netQuantity);return(minQ==null||(q!=null&&q>=minQ))&&(maxQ==null||(q!=null&&q<=maxQ));}));}catch(e){res.status(500).json({error:e.message})}});
router.get("/:id",async(req,res)=>{try{const product=await prisma.product.findFirst({where:{id:req.params.id,...visibility(req)},include:{owner:{select:{id:true,name:true,email:true}},category:{include:{parent:{include:{parent:{include:{parent:true}}}}}},inspections:{include:{shop:true,worker:{select:{id:true,name:true}}},orderBy:{inspectedAt:"desc"}}}});if(!product)return res.status(404).json({error:"Product not found"});res.json(product);}catch(e){res.status(500).json({error:e.message})}});
router.post("/",async(req,res)=>{try{const b=req.body||{};if(!b.categoryId||!String(b.productName||"").trim())return res.status(400).json({error:"Category and product name are required"});const category=await prisma.category.findFirst({where:{id:b.categoryId,OR:[{isSystem:true},{ownerId:req.user.id}]}});if(!category)return res.status(404).json({error:"Product category not found"});const verification=verifyProduct(b);const source=String(b.sourceType||category.sourceType||"OFFLINE").toUpperCase()==="ECOMMERCE"?"ECOMMERCE":"OFFLINE";const imageUrls=Array.isArray(b.imageUrls)?b.imageUrls:[];const product=await prisma.$transaction(async tx=>{let shopId=null;if(source==="OFFLINE"){const shop=await tx.shop.create({data:{name:String(b.shopName||"Unnamed shop").trim(),address:b.shopAddress?.trim()||null,city:b.shopCity?.trim()||null,state:b.shopState?.trim()||null,sourceType:"OFFLINE",ownerId:req.user.id}});shopId=shop.id;}else if(b.sourceWebsiteName){const shop=await tx.shop.create({data:{name:String(b.sourceWebsiteName).trim(),sourceType:"ECOMMERCE",ownerId:req.user.id}});shopId=shop.id;}const p=await tx.product.create({data:{categoryId:b.categoryId,ownerId:req.user.id,brandName:String(b.brandName||"").trim()||null,productName:String(b.productName).trim(),description:String(b.description||"").trim()||null,ocrData:b.ocrData?JSON.stringify(b.ocrData):null,netQuantity:String(b.netQuantity||"").trim()||null,unit:String(b.unit||"").trim()||null,mrp:b.mrp===""||b.mrp==null?null:Number(b.mrp),barcode:String(b.barcode||"").trim()||null,imageUrls,complianceStatus:b.complianceStatus||verification.status,violationReason:b.violationReason||verification.reason,sourceType:source,sourceUrl:b.sourceUrl||null,sourceWebsiteName:b.sourceWebsiteName||null},include:{category:true}});if(shopId)await tx.inspection.create({data:{workerId:req.user.id,shopId,productId:p.id,status:b.complianceStatus||verification.status,notes:b.notes||b.violationReason||verification.reason}});return p;});res.status(201).json({product,id:product.id});}catch(e){res.status(500).json({error:e.message||"Failed to register product"})}});
router.delete("/:id",async(req,res)=>{try{const p=await prisma.product.findFirst({where:{id:req.params.id,...visibility(req)}});if(!p)return res.status(404).json({error:"Product not found"});await prisma.$transaction(async tx=>{await tx.inspection.deleteMany({where:{productId:p.id}});await tx.product.delete({where:{id:p.id}})});res.json({message:"Product deleted"});}catch(e){res.status(500).json({error:e.message})}});
export default router;
