import type { RuleDefinition, RuleCondition } from '../../domain/types.js';
import { SOURCES } from './sources.js';

const c = (conditionId: string, targetField: string, operator: RuleCondition['operator'], errorMessage: string, violationReason: string, expectedValue?: unknown): RuleCondition => ({ conditionId, targetField, operator, errorMessage, violationReason, expectedValue });
const ref = (...ids: (keyof typeof SOURCES)[]) => ids.map(id => SOURCES[id]);
const contexts = (values: NonNullable<RuleDefinition['versions'][number]['applicabilityCriteria']['contexts']>) => ({ contexts: values });

export const RULES: RuleDefinition[] = [
  { ruleId:'PCR-R3', ruleCode:'PCR-R3-APPLICABILITY', ruleNumber:'3', title:'Applicability and exclusions', description:'Chapter II applicability depends on the package and consumer categories specified by Rule 3.', category:'APPLICABILITY', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:{}, conditions:[ c('r3-industrial','productMetadata.consumerType','EQUALS','Industrial-consumer status must be evaluated.','Package is identified as intended for an industrial consumer.','industrial'), c('r3-institutional','productMetadata.consumerType','EQUALS','Institutional-consumer status must be evaluated.','Package is identified as intended for an institutional consumer.','institutional') ] }] },
  { ruleId:'PCR-R4', ruleCode:'PCR-R4-DECLARATION', ruleNumber:'4', title:'Mandatory declarations on pre-packaged commodities', description:'Packages must carry the declarations required by the Rules before being pre-packed for sale, distribution or delivery, subject to the rule explanations.', category:'GENERAL_DECLARATION', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011','AMEND_2026_418E'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[ c('r4-retail-price','declarations.retailSalePrice','EXISTS','Retail sale price evidence is required.','Required retail sale price declaration could not be established.'), c('r4-manufacturer','declarations.manufacturerOrPacker','EXISTS','Manufacturer/packer/importer identity is required.','Required manufacturer, packer or importer declaration is missing.'), c('r4-generic-name','declarations.commonOrGenericName','EXISTS','Common or generic name is required.','Common/generic commodity name is missing.'), c('r4-net-quantity','declarations.netQuantity','EXISTS','Net quantity is required.','Net quantity declaration is missing.') ] }] },
  { ruleId:'PCR-R6-1-A', ruleCode:'PCR-R6-1-A-MANUFACTURER', ruleNumber:'6(1)(a)', title:'Manufacturer, packer and importer declaration', description:'The package must declare the responsible manufacturer/packer identity and applicable importer information.', category:'MANUFACTURER_PACKER_IMPORTER', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-1-a-identity','declarations.manufacturerOrPacker','EXISTS','Manufacturer/packer/importer declaration is required.','Required identity and address declaration is not established.')] }] },
  { ruleId:'PCR-R6-1-B', ruleCode:'PCR-R6-1-B-GENERIC-NAME', ruleNumber:'6(1)(b)', title:'Common or generic name', description:'The package shall bear the common or generic name of the commodity.', category:'GENERAL_DECLARATION', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-1-b','declarations.commonOrGenericName','EXISTS','Common/generic name is required.','Rule 6(1)(b) declaration is not established.')] }] },
  { ruleId:'PCR-R6-1-C', ruleCode:'PCR-R6-1-C-NET-QUANTITY', ruleNumber:'6(1)(c)', title:'Net quantity declaration', description:'The package shall declare net quantity in the prescribed standard unit or by number where appropriate.', category:'NET_QUANTITY', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-1-c-exists','declarations.netQuantity','EXISTS','Net quantity declaration is required.','Rule 6(1)(c) net quantity is not established.'), c('r6-1-c-unit','declarations.netQuantityUnit','VALID_UNIT','Net quantity unit is invalid or unavailable.','Declared quantity is not expressed in a recognized standard unit.')] }] },
  { ruleId:'PCR-R6-1-D', ruleCode:'PCR-R6-1-D-DATE', ruleNumber:'6(1)(d)', title:'Month and year declaration', description:'The package shall declare the month and year of manufacture, pre-packing or import, subject to commodity-specific exceptions.', category:'DATE', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-1-d','declarations.manufactureOrImportDate','VALID_DATE_FORMAT','Manufacture/pre-pack/import date is missing or invalid.','Rule 6(1)(d) date declaration could not be verified.')] }] },
  { ruleId:'PCR-R6-1-E', ruleCode:'PCR-R6-1-E-MRP', ruleNumber:'6(1)(e)', title:'Retail sale price', description:'The package shall bear the retail sale price in the manner required by the Rules.', category:'MRP', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-1-e','declarations.retailSalePrice','VALID_CURRENCY','MRP is missing or invalid.','Rule 6(1)(e) retail sale price could not be verified.')] }] },
  { ruleId:'PCR-R6-1-F', ruleCode:'PCR-R6-1-F-DIMENSIONS', ruleNumber:'6(1)(f)', title:'Dimensions where relevant', description:'Where size is relevant, the prescribed dimensions shall be declared.', category:'DIMENSIONS', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-1-f','declarations.dimensions','EXISTS','Dimension declaration is required where size is relevant.','Required dimensions could not be established.')] }] },
  { ruleId:'PCR-R6-2', ruleCode:'PCR-R6-2-CONSUMER-CONTACT', ruleNumber:'6(2)', title:'Consumer complaint contact', description:'Consumer complaint contact details shall be declared as prescribed.', category:'GENERAL_DECLARATION', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-2','declarations.consumerComplaintContact','EXISTS','Consumer complaint contact is required.','Rule 6(2) contact declaration could not be established.')] }] },
  { ruleId:'PCR-R6-3', ruleCode:'PCR-R6-3-STICKER', ruleNumber:'6(3)', title:'Restrictions on separate stickers', description:'Required declarations shall not be made by prohibited separate stickers; the permitted revised MRP sticker is subject to its own conditions.', category:'PRESENTATION', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r6-3','visual.stickerCompliance','VISUAL_CHECK','Sticker presentation requires visual verification.','A prohibited sticker or an obscured original declaration may be present.',true)] }] },
  { ruleId:'PCR-R6-10A-2026', ruleCode:'PCR-R6-10A-COUNTRY-OF-ORIGIN-FILTER', ruleNumber:'6(10A)', title:'Country-of-origin filter for imported products on e-commerce', description:'The e-commerce country-of-origin filter requirement is governed by dated 2026 amendments.', category:'E_COMMERCE', defaultSeverity:'HIGH', enabled:true, versions:[
      { version:1, effectiveFrom:'2026-07-01', effectiveUntil:'2027-06-30', status:'SUPERSEDED', legalSources:ref('AMEND_2026_128E'), applicabilityCriteria:contexts(['ecommerce_listing','both']), conditions:[c('r6-10a-filter','ecommerce.countryOfOriginFilter','VISUAL_CHECK','Country-of-origin searchable/sortable filter is required.','Required country-of-origin filter could not be verified.',true)] },
      { version:2, effectiveFrom:'2027-07-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('AMEND_2026_312E'), applicabilityCriteria:contexts(['ecommerce_listing','both']), conditions:[c('r6-10a-filter-2027','ecommerce.countryOfOriginFilter','VISUAL_CHECK','Country-of-origin searchable/sortable filter is required.','The imported product listing does not establish the required country-of-origin filter.',true)] }
    ] },
  { ruleId:'PCR-R7', ruleCode:'PCR-R7-DECLARATION-HEIGHT', ruleNumber:'7', title:'Principal display panel and declaration dimensions', description:'Declarations on the principal display panel must meet the prescribed presentation and size requirements.', category:'PRESENTATION', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r7-visual','visual.declarationLegibility','VISUAL_CHECK','Declaration dimensions require visual verification.','Required declaration height, placement or legibility could not be verified.',true)] }] },
  { ruleId:'PCR-R8', ruleCode:'PCR-R8-PDP', ruleNumber:'8', title:'Declarations on principal display panel', description:'Required declarations shall appear on the principal display panel in the prescribed manner.', category:'PRESENTATION', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r8','visual.principalDisplayPanel','VISUAL_CHECK','Principal display panel placement requires visual verification.','Required declarations could not be verified on the principal display panel.',true)] }] },
  { ruleId:'PCR-R9', ruleCode:'PCR-R9-LEGIBILITY', ruleNumber:'9', title:'Legibility and language of declarations', description:'Declarations must be legible, prominent and presented in the permitted manner.', category:'PRESENTATION', defaultSeverity:'MEDIUM', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r9','visual.legibility','VISUAL_CHECK','Legibility requires visual verification.','Required declarations may not be legible or prominent.',true)] }] },
  { ruleId:'PCR-R10', ruleCode:'PCR-R10-MANUFACTURER-ADDRESS', ruleNumber:'10', title:'Manufacturer/packer/importer address presentation', description:'The responsible entity name and complete address shall be declared in the prescribed manner.', category:'MANUFACTURER_PACKER_IMPORTER', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2011-04-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('PRINCIPAL_2011'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r10','declarations.completeAddress','EXISTS','Complete address is required.','Required manufacturer/packer/importer address could not be established.')] }] },
  { ruleId:'PCR-R12-6', ruleCode:'PCR-R12-6-NON-MISLEADING-QUANTITY', ruleNumber:'12(6)', title:'Quantity expression must not be exaggerated or misleading', description:'Quantity expressions must not create an exaggerated, misleading or inadequate impression.', category:'NET_QUANTITY', defaultSeverity:'HIGH', enabled:true, versions:[{ version:1, effectiveFrom:'2012-07-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('AMEND_2011_784E'), applicabilityCriteria:contexts(['physical_package','both']), conditions:[c('r12-6','declarations.quantityExpression','VISUAL_CHECK','Quantity expression requires visual/context verification.','The quantity expression may create an exaggerated, misleading or inadequate impression.',true)] }] },
  { ruleId:'PCR-R26-A-PAN-MASALA', ruleCode:'PCR-R26-A-PAN-MASALA', ruleNumber:'26(a)', title:'Pan masala exception', description:'From 1 February 2026, the specified Rule 26(a) clause does not apply to pan masala.', category:'COMMODITY_SPECIFIC', defaultSeverity:'INFO', enabled:true, versions:[{ version:1, effectiveFrom:'2026-02-01', effectiveUntil:null, status:'ACTIVE', legalSources:ref('AMEND_2025_881E'), applicabilityCriteria:{ includedCommodities:['pan masala'] }, conditions:[c('r26-pan','rule26.exemptionClaimed','NOT_EQUALS','Pan masala is outside the specified Rule 26(a) exemption.','The prohibited small-package exemption was claimed for pan masala.',true)] }] }
];

export const RULESET_VERSION = '2026.09.02';
