import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../lib/auth";
import "../styles/products.css";

const API_URL = "http://localhost:5000/api";
function flatten(nodes, path = []) { return nodes.flatMap((n) => { const next = [...path, n]; return [{ ...n, path: next }, ...flatten(n.children || [], next)]; }); }
function TreeNode({ node, onDelete }) { return <div className="category-tree-node"><div className="category-item"><div className="category-card"><h3>{node.name}</h3><p>{node.sourceType === "ECOMMERCE" ? "E-commerce" : "Offline"} · {node.isFinalProductType ? "Final category" : "Category"} · {node.isSystem ? "Global" : "Private"}</p></div><button className="delete-category-button" type="button" onClick={() => onDelete(node)}>Delete</button></div>{node.children?.length ? <div className="category-tree-children">{node.children.map((child) => <TreeNode key={child.id} node={child} onDelete={onDelete} />)}</div> : null}</div>; }

function AdminCategories() {
  const [tree, setTree] = useState([]); const [selected, setSelected] = useState(""); const [name, setName] = useState(""); const [final, setFinal] = useState(false); const [sourceType, setSourceType] = useState("OFFLINE"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false);
  async function load() { setLoading(true); const r = await apiFetch(`${API_URL}/categories/tree/all`); const d = await r.json().catch(() => []); if (r.ok) setTree(d); else setMessage(d.error || "Could not load categories"); setLoading(false); }
  useEffect(() => { load(); }, []);
  const options = useMemo(() => flatten(tree), [tree]);
  const parent = options.find((x) => x.id === selected);
  async function add() { const clean = name.trim(); if (!clean || creating) return setMessage("Category name is required"); if (parent && parent.sourceType !== sourceType) return setMessage("A subcategory must use the same source type as its parent."); setCreating(true); setMessage(""); try { const r = await apiFetch(`${API_URL}/categories`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: clean, parentId: selected || null, isFinal: final, sourceType, global: true }) }); const d = await r.json().catch(() => null); if (!r.ok) return setMessage(d?.error || "Could not create global category"); setName(""); setFinal(false); setSelected(""); setMessage("Global category created for every user."); await load(); } finally { setCreating(false); } }
  async function remove(category) { if (!window.confirm(`Delete ${category.name}? Products in this branch will be moved to Uncategorized and descendant category nodes will be removed.`)) return; const r = await apiFetch(`${API_URL}/categories/${category.id}`, { method: "DELETE" }); const d = await r.json().catch(() => null); setMessage(r.ok ? (d?.message || "Category deleted") : (d?.error || "Delete failed")); if (r.ok) load(); }
  return <div className="products-page"><div className="page-header"><p className="eyebrow">ADMIN</p><h1>Global categories</h1><p>Global categories are available to every user. Choose Offline or E-commerce for each branch.</p></div><section className="product-actions category-toolbar"><label><span>Source</span><select value={sourceType} onChange={(e) => setSourceType(e.target.value)}><option value="OFFLINE">Offline</option><option value="ECOMMERCE">E-commerce</option></select></label><label><span>Parent category</span><select value={selected} onChange={(e) => { setSelected(e.target.value); const p = options.find((x) => x.id === e.target.value); if (p) setSourceType(p.sourceType); }}><option value="">Level 1 category</option>{options.filter((x) => !x.isFinalProductType && x.path.length < 4 && x.isSystem).map((x) => <option key={x.id} value={x.id}>{x.path.map((p) => p.name).join(" → ")} · {x.sourceType === "ECOMMERCE" ? "E-commerce" : "Offline"}</option>)}</select></label><input placeholder="Category name" value={name} onChange={(e) => setName(e.target.value)} disabled={creating} /><label className="checkbox-field"><input type="checkbox" checked={final} onChange={(e) => setFinal(e.target.checked)} disabled={creating} /><span>Final category</span></label><button className="primary-button" type="button" onClick={add} disabled={creating || !name.trim()}>{creating ? "Creating..." : "Add global category"}</button></section>{message && <div className="status-message">{message}</div>}<section className="product-categories"><div className="section-heading"><div><h2>Global category tree</h2><p>Deleting a branch preserves products by moving them to the appropriate Uncategorized category.</p></div></div>{loading ? <p>Loading...</p> : tree.length ? <div className="category-tree">{tree.map((root) => <TreeNode key={root.id} node={root} onDelete={remove} />)}</div> : <p>No global categories yet.</p>}</section></div>;
}
export default AdminCategories;
