import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/auth";
import "../styles/admin-dashboard.css";
import "../styles/admin-dashboard-modern.css";

const API_URL = "http://localhost:5000/api";

function BarList({ items = [], labelKey, valueKey, empty = "No data yet." }) { const max = Math.max(...items.map((item) => Number(item?.[valueKey] || 0)), 1); if (!items.length) return <p className="admin-empty">{empty}</p>; return <div className="admin-bars">{items.map((item, index) => <div className="admin-bar-row" key={`${String(item?.[labelKey])}-${index}`}><div className="admin-bar-label"><span>{item?.[labelKey] || "Unknown"}</span><b>{item?.[valueKey] ?? 0}</b></div><div className="admin-bar-track"><span style={{ width: `${Math.max(5, (Number(item?.[valueKey] || 0) / max) * 100)}%` }} /></div></div>)}</div>; }
function AdminStat({ label, value, tone = "neutral", helper }) { return <div className={`admin-stat-card ${tone}`}><span>{label}</span><strong>{value ?? 0}</strong>{helper && <small>{helper}</small>}</div>; }

export default function AdminDashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const r = await apiFetch(`${API_URL}/admin/overview`); const d = await r.json().catch(() => ({})); if (!r.ok) throw new Error(d.error || "Could not load admin dashboard"); setData(d); } catch (e) { setError(e?.message || "Could not load admin dashboard"); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  if (error) return <main className="admin-dashboard admin-dashboard-modern"><div className="admin-error">{error}<button type="button" className="admin-retry" onClick={load}>Retry</button></div></main>;
  if (loading || !data) return <main className="admin-dashboard admin-dashboard-modern"><div className="admin-loading"><div className="admin-loading-orb" /><h2>Loading PARAKH control center</h2><p>Preparing platform and compliance activity.</p></div></main>;
  const c = data.counts || {}; const a = data.analytics || {}; const statusItems = Array.isArray(a.inspectionStatuses) ? a.inspectionStatuses : [];
  const complianceRate = Number(c.products) > 0 ? Math.min(100, Math.round((Number(c.compliant || 0) / Number(c.products)) * 100)) : 0;
  const ecommerceInspections = (data.recentInspections || []).filter((x) => String(x.sourceType || "OFFLINE").toUpperCase() === "ECOMMERCE"); const statusText = (value) => String(value || "NEEDS_REVIEW").replaceAll("_", " ");

  return <main className="admin-dashboard admin-dashboard-modern">
    <header className="admin-hero"><div><p className="card-kicker">PARAKH · ADMIN CONTROL CENTER</p><h1>Platform oversight without losing the product hierarchy.</h1><p>Monitor inspections, compliance patterns, registered products, e-commerce activity and the shared category structure from one workspace.</p></div><div className="admin-hero-actions"><button type="button" className="admin-secondary" onClick={load}>Refresh data</button><Link className="admin-primary" to="/admin/categories">Manage hierarchy</Link></div></header>
    <section className="admin-stat-grid"><AdminStat label="Users" value={c.users} helper="Registered accounts" /><AdminStat label="Products" value={c.products} helper="All registered records" /><AdminStat label="Inspections" value={c.inspections} helper="Recorded checks" /><AdminStat label="Compliance rate" value={`${complianceRate}%`} tone="success" helper="Current platform rate" /><AdminStat label="Offline products" value={c.offlineProducts} helper="Physical inspections" /><AdminStat label="E-commerce products" value={c.ecommerceProducts} helper="Online listings" /><AdminStat label="Violations" value={c.violations} tone="danger" helper="Recorded non-compliance" /><AdminStat label="Needs review" value={c.review} tone="warning" helper="Awaiting verification" /></section>
    <section className="admin-command-grid"><Link className="admin-command primary" to="/admin/categories"><span>01</span><div><small>STRUCTURE</small><strong>Global product hierarchy</strong><em>Main category → subcategory → final product type</em></div><b>→</b></Link><Link className="admin-command" to="/products"><span>02</span><div><small>DATABASE</small><strong>Registered products</strong><em>Browse product records and source split</em></div><b>→</b></Link><Link className="admin-command" to="/reports"><span>03</span><div><small>EVIDENCE</small><strong>Compliance reports</strong><em>Review and export inspection findings</em></div><b>→</b></Link><Link className="admin-command" to="/ecommerce-products"><span>04</span><div><small>ONLINE</small><strong>E-commerce database</strong><em>Inspect listing categories and sources</em></div><b>→</b></Link></section>
    <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">LIVE ACTIVITY</p><h2>Recent inspections</h2><p>Latest offline and e-commerce activity.</p></div><Link to="/history">History →</Link></div><div className="admin-list">{(data.recentInspections || []).map((x) => { const ecommerce = String(x.sourceType || "OFFLINE").toUpperCase() === "ECOMMERCE"; const source = ecommerce ? (x.sourceWebsiteName || x.sourceUrl || "E-commerce source") : (x.shop?.name || "Unknown shop"); return <Link className="admin-list-row" to={x.product?.id ? `/products/item/${x.product.id}` : "/history"} key={x.id}><div><strong>{x.product?.productName || "Unnamed product"}</strong><span>{ecommerce ? "E-COMMERCE" : "OFFLINE"} · {source} · {x.worker?.name || "Unknown user"}</span><small>{x.inspectedAt ? new Date(x.inspectedAt).toLocaleString() : "Date unavailable"}</small></div><b className={`admin-status-pill ${(x.status || "NEEDS_REVIEW").toLowerCase()}`}>{statusText(x.status)}</b></Link>; })}{!data.recentInspections?.length && <p className="admin-empty">No inspections yet.</p>}</div></section><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">OUTCOMES</p><h2>Inspection status</h2><p>Current outcome distribution.</p></div></div><BarList items={statusItems} labelKey="status" valueKey="count" /></section></div>
    <section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">ONLINE MONITORING</p><h2>E-commerce listing details</h2><p>Recent online sources, declarations and category context.</p></div><Link to="/ecommerce-products">Open database →</Link></div>{ecommerceInspections.length ? <div className="admin-ecommerce-grid">{ecommerceInspections.map((x) => <div className="admin-ecommerce-card" key={x.id}><div className="admin-ecommerce-card-head"><div><strong>{x.product?.productName || "Unnamed product"}</strong><span>{x.sourceWebsiteName || "Website not recorded"}</span></div><span className={`admin-status-pill ${(x.product?.complianceStatus || x.status || "NEEDS_REVIEW").toLowerCase()}`}>{statusText(x.product?.complianceStatus || x.status)}</span></div><div className="admin-ecommerce-fields"><div><span>Category</span><b>{x.product?.category?.name || "Not recorded"}</b></div><div><span>Brand</span><b>{x.product?.brandName || "Not recorded"}</b></div><div><span>Quantity</span><b>{x.product?.netQuantity || "-"} {x.product?.unit || ""}</b></div><div><span>MRP</span><b>{x.product?.mrp != null ? `₹${x.product.mrp}` : "Not recorded"}</b></div><div><span>GTIN / Barcode</span><b>{x.product?.barcode || "Not recorded"}</b></div></div>{x.sourceUrl && <a className="admin-ecommerce-url" href={x.sourceUrl} target="_blank" rel="noreferrer">Open source listing ↗</a>}</div>)}</div> : <p className="admin-empty">No recent e-commerce inspections yet.</p>}</section>
    <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">HIERARCHY</p><h2>Top categories</h2><p>Product distribution across the shared structure.</p></div><Link to="/admin/categories">Manage →</Link></div><div className="admin-ranking">{(data.topCategories || []).slice(0,8).map((x, i) => <div className="admin-rank-row" key={x.categoryId || i}><i>{String(i + 1).padStart(2,"0")}</i><span>{x.name}</span><b>{x.products}</b></div>)}{!data.topCategories?.length && <p className="admin-empty">No products yet.</p>}</div></section><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">SOURCE MIX</p><h2>Product source split</h2><p>Offline vs e-commerce records.</p></div></div><div className="admin-status-grid"><div><span>OFFLINE</span><b>{c.offlineProducts ?? 0}</b></div><div><span>E-COMMERCE</span><b>{c.ecommerceProducts ?? 0}</b></div></div><div className="admin-source-meter"><span style={{width:`${Number(c.products) ? Math.min(100,(Number(c.offlineProducts || 0)/Number(c.products))*100) : 0}%`}} /></div></section></div>
    <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">PATTERNS</p><h2>Top brands</h2><p>Most frequent brands in stored records.</p></div></div><BarList items={a.topBrands || []} labelKey="brand" valueKey="products" /></section><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">GEOGRAPHY</p><h2>Violations by location</h2><p>Offline locations and online source activity.</p></div></div><BarList items={a.locationViolations || []} labelKey="location" valueKey="violations" /></section></div>
    <section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">COMPLIANCE TREND</p><h2>Violation trend</h2><p>Monthly violation activity from stored inspections.</p></div></div><BarList items={a.violationTrend || []} labelKey="month" valueKey="violations" empty="No monthly violation data yet." /></section>
    <div className="admin-columns"><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">REPEAT PATTERNS</p><h2>Repeat violations</h2><p>Products with repeated violation activity.</p></div><Link to="/history">Inspect →</Link></div><BarList items={a.repeatViolations || []} labelKey="shop" valueKey="repeatViolations" empty="No repeat-violation patterns detected." /></section><section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">OFFICER QUEUE</p><h2>Pending verification</h2><p>Records requiring further review.</p></div></div><div className="admin-pending"><strong>{a.pendingVerification ?? c.review ?? 0}</strong><span>products requiring review</span><div className="admin-pending-track"><span style={{ width: `${Math.min(100, ((a.pendingVerification ?? c.review ?? 0) / Math.max(1, Number(c.products || 0))) * 100)}%` }} /></div></div><div className="admin-status-grid">{statusItems.filter((x) => ["NEEDS_REVIEW", "UNABLE_TO_VERIFY"].includes(x.status)).map((x) => <div key={x.status}><span>{statusText(x.status)}</span><b>{x.count}</b></div>)}</div></section></div>
    <section className="admin-panel"><div className="admin-panel-head"><div><p className="card-kicker">RULES ENGINE</p><h2>Frequent rule violations</h2><p>Stored findings from offline and e-commerce inspections.</p></div><Link to="/reports">Reports →</Link></div><div className="admin-rule-grid">{(data.topRules || []).map((x, i) => <div className="admin-rule" key={`${x.rule}-${i}`}><strong>{x.rule}</strong><span>{x.count} violation{x.count === 1 ? "" : "s"}</span></div>)}{!data.topRules?.length && <p className="admin-empty">No violations yet.</p>}</div></section>
  </main>;
}
