import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { apiFetch, getUser } from "../lib/auth";
import "../styles/products.css";
const API_URL = "http://localhost:5000/api";
const pathOf = c => [c?.parent?.parent?.parent,c?.parent?.parent,c?.parent,c].filter(Boolean).map(x=>x.name).join(" → ");
export default function CategoryPage(){
 const {categoryId}=useParams(),user=getUser();
 const [category,setCategory]=useState(null),[childName,setChildName]=useState(""),[childFinal,setChildFinal]=useState(false),[showChild,setShowChild]=useState(false),[message,setMessage]=useState(""),[advancedSelect,setAdvancedSelect]=useState(false),[selected,setSelected]=useState([]),[filters,setFilters]=useState({status:"ALL",productName:"",brand:"",shop:"",unit:"",minQ:"",maxQ:"",minMrp:"",maxMrp:"",dateFrom:"",dateTo:""});
 async function load(){const r=await apiFetch(`${API_URL}/categories/id/${categoryId}`);const d=await r.json().catch(()=>null);if(r.ok)setCategory(d);else setMessage(d?.error||"Category not found");}
 useEffect(()=>{load();setSelected([])},[categoryId]);
 const depth=useMemo(()=>{let d=1,p=category?.parent;while(p){d++;p=p.parent}return d},[category]),children=category?.children||[],isFinal=!!category?.isFinalProductType,canManageGlobal=category?.isSystem&&user?.role==="ADMIN",canAddChild=!isFinal&&depth<4;
 const products=(category?.products||[]).filter(p=>{const shop=p.inspections?.[0]?.shop?.name||"",q=parseFloat(String(p.netQuantity||"").replace(/[^0-9.]/g,"")),dt=new Date(p.inspections?.[0]?.inspectedAt||p.createdAt);return(filters.status==="ALL"||p.complianceStatus===filters.status)&&(p.productName||"").toLowerCase().includes(filters.productName.toLowerCase())&&(p.brandName||"").toLowerCase().includes(filters.brand.toLowerCase())&&shop.toLowerCase().includes(filters.shop.toLowerCase())&&(!filters.unit||(p.unit||"").toLowerCase()===filters.unit.toLowerCase())&&(!filters.minQ||q>=+filters.minQ)&&(!filters.maxQ||q<=+filters.maxQ)&&(!filters.minMrp||p.mrp>=+filters.minMrp)&&(!filters.maxMrp||p.mrp<=+filters.maxMrp)&&(!filters.dateFrom||dt>=new Date(filters.dateFrom+"T00:00:00"))&&(!filters.dateTo||dt<=new Date(filters.dateTo+"T23:59:59.999"))});
 const all=products.length&&products.every(p=>selected.includes(p.id));
 const setF=(k,v)=>{setFilters(x=>({...x,[k]:v}));setSelected([])};
 async function addChild(){if(!childName.trim()||!canAddChild)return;const r=await apiFetch(`${API_URL}/categories`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:childName,parentId:category.id,isFinal:childFinal,sourceType:category.sourceType,global:!!canManageGlobal})});const d=await r.json().catch(()=>null);if(!r.ok)return setMessage(d?.error||"Could not add category");setChildName("");setChildFinal(false);setShowChild(false);setMessage(canManageGlobal?"Global subcategory added.":"Private subcategory added to this global category.");load()}
 async function delCategory(id){if(!confirm("Delete this category branch? Registered products will be moved to the appropriate Uncategorized category."))return;const r=await apiFetch(`${API_URL}/categories/${id}`,{method:"DELETE"});const d=await r.json().catch(()=>null);if(!r.ok)return setMessage(d?.error||"Delete failed");location.href=category.parent?`/products/category/${category.parent.id}`:"/products"}
 async function delProducts(){if(!selected.length||!confirm(`Delete ${selected.length} product(s)?`))return;for(const id of selected){const r=await apiFetch(`${API_URL}/products/${id}`,{method:"DELETE"});if(!r.ok){const d=await r.json().catch(()=>null);setMessage(d?.error||"Delete failed");break}}setSelected([]);load()}
 if(!category)return <div className="products-page"><p>{message||"Loading..."}</p></div>;
 return <div className="products-page"><Link className="back-link" to={category.parent?`/products/category/${category.parent.id}`:"/products"}>← Back</Link><div className="page-header"><p className="eyebrow">PRODUCT DATABASE · LEVEL {depth}</p><h1>{category.name}</h1><p>{pathOf(category)}</p><p>{category.isSystem?"GLOBAL":"PRIVATE"} · {category.sourceType==="ECOMMERCE"?"E-COMMERCE":"OFFLINE"} · {isFinal?"FINAL PRODUCT CATEGORY":"SUBCATEGORY"}</p></div>{message&&<div className="status-message">{message}</div>}
 {(canAddChild||!category.isSystem||canManageGlobal)&&<section className="product-actions category-toolbar">{canAddChild&&<button className="secondary-action" onClick={()=>setShowChild(v=>!v)}>{canManageGlobal?"+ Add global subcategory":"+ Add private subcategory"}</button>}{(!category.isSystem||canManageGlobal)&&<button className="delete-category-button" onClick={()=>delCategory(category.id)}>Delete category</button>}</section>}
 {showChild&&<div className="category-form"><input placeholder="New subcategory" value={childName} onChange={e=>setChildName(e.target.value)}/><label><input type="checkbox" checked={childFinal} onChange={e=>setChildFinal(e.target.checked)}/> Set as final product type</label><button onClick={addChild}>Add</button><span className="gesture-hint">Source: {category.sourceType==="ECOMMERCE"?"E-commerce":"Offline"}</span></div>}
 {!isFinal&&<section className="product-categories"><div className="section-heading"><div><h2>Subcategories</h2><p>Global categories can contain private user subcategories. Maximum depth is four.</p></div></div><div className="category-grid">{children.map(c=><div className="category-item" key={c.id}><Link className="category-card" to={`/products/category/${c.id}`}><h3>{c.name}</h3><p>{c.isSystem?"Global":"Private to your account"} · {c.sourceType==="ECOMMERCE"?"E-commerce":"Offline"} · {c.isFinalProductType?"Final category":`Level ${depth+1}`}</p></Link>{(!c.isSystem||canManageGlobal)&&<button className="delete-category-button" onClick={()=>delCategory(c.id)}>Delete</button>}</div>)}</div>{!children.length&&<p>No subcategories yet.</p>}</section>}
 {isFinal&&<section className="product-categories"><div className="section-heading"><div><h2>Registered {category.name} products</h2><p>{products.length} products match the current filters.</p></div></div><div className="filter-panel"><input placeholder="Product" value={filters.productName} onChange={e=>setF("productName",e.target.value)}/><input placeholder="Brand" value={filters.brand} onChange={e=>setF("brand",e.target.value)}/><input placeholder="Shop" value={filters.shop} onChange={e=>setF("shop",e.target.value)}/><select value={filters.status} onChange={e=>setF("status",e.target.value)}><option>ALL</option><option>OKAY</option><option>VIOLATION</option><option>NEEDS_REVIEW</option></select><select value={filters.unit} onChange={e=>setF("unit",e.target.value)}><option value="">Any unit</option><option value="mg">mg</option><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="L">L</option><option value="pcs">pcs</option><option value="dozen">dozen</option><option value="m">m</option></select><input type="number" placeholder="Min quantity" value={filters.minQ} onChange={e=>setF("minQ",e.target.value)}/><input type="number" placeholder="Max quantity" value={filters.maxQ} onChange={e=>setF("maxQ",e.target.value)}/><input type="number" placeholder="Min MRP" value={filters.minMrp} onChange={e=>setF("minMrp",e.target.value)}/><input type="number" placeholder="Max MRP" value={filters.maxMrp} onChange={e=>setF("maxMrp",e.target.value)}/><label className="filter-date"><span>From date</span><input type="date" value={filters.dateFrom} onChange={e=>setF("dateFrom",e.target.value)}/></label><label className="filter-date"><span>To date</span><input type="date" value={filters.dateTo} onChange={e=>setF("dateTo",e.target.value)}/></label></div><div className="bulk-toolbar" onContextMenu={e=>{e.preventDefault();setAdvancedSelect(true)}}><span className="gesture-hint">{advancedSelect?"Selection controls unlocked":"Long-press or right-click this bar for selection controls"}</span>{advancedSelect&&<label><input type="checkbox" checked={!!all} onChange={()=>setSelected(all?[]:products.map(p=>p.id))}/> Select all matching</label>}{advancedSelect&&selected.length>0&&<button className="delete-category-button" onClick={delProducts}>Delete selected ({selected.length})</button>}</div><div className="product-list">{products.map(p=><div className="product-row" key={p.id}>{advancedSelect&&<input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])}/>}<Link to={`/products/item/${p.id}`}><div><strong>{p.productName}</strong><span>{p.brandName||"Brand not recorded"}</span></div><div><span>{p.netQuantity||"-"} {p.unit||""}</span><span>₹{p.mrp??"-"} · {p.inspections?.[0]?.shop?.name||"Shop not recorded"}</span></div><span className={`compliance-badge ${p.complianceStatus.toLowerCase()}`}>{p.complianceStatus}</span></Link></div>)}</div></section>}
 </div>;
}
