import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useParams, useSearchParams } from "react-router-dom";
import { apiFetch, getUser } from "../lib/auth";
import "../styles/products.css";
const API_URL = "http://localhost:5000/api";
const pathOf = c => [c?.parent?.parent?.parent,c?.parent?.parent,c?.parent,c].filter(Boolean).map(x=>x.name).join(" → ");
export default function CategoryPage(){
 const {categoryId}=useParams(),location=useLocation(),[searchParams]=useSearchParams(),user=getUser();
 const globalManagement=location.pathname.startsWith("/admin/categories/")&&searchParams.get("globalAdmin")==="1"&&user?.role==="ADMIN";
 const [category,setCategory]=useState(null),[childName,setChildName]=useState(""),[childFinal,setChildFinal]=useState(false),[showChild,setShowChild]=useState(false),[message,setMessage]=useState(""),[advancedSelect,setAdvancedSelect]=useState(false),[selected,setSelected]=useState([]),[deleting,setDeleting]=useState(false),[filters,setFilters]=useState({status:"ALL",productName:"",brand:"",shop:"",unit:"",minQ:"",maxQ:"",minMrp:"",maxMrp:"",dateFrom:"",dateTo:""});
 async function load(){const r=await apiFetch(`${API_URL}/categories/id/${categoryId}`);const d=await r.json().catch(()=>null);if(r.ok)setCategory(d);else setMessage(d?.error||"Category not found");}
 useEffect(()=>{load();setSelected([])},[categoryId]);
 const depth=useMemo(()=>{let d=1,p=category?.parent;while(p){d++;p=p.parent}return d},[category]),children=category?.children||[],isFinal=!!category?.isFinalProductType,canManageGlobal=globalManagement&&category?.isSystem,canAddChild=!isFinal&&depth<4;
 const products=(category?.products||[]).filter(p=>{const shop=p.inspections?.[0]?.shop?.name||"",q=parseFloat(String(p.netQuantity||"").replace(/[^0-9.]/g,"")),dt=new Date(p.inspections?.[0]?.inspectedAt||p.createdAt);return(filters.status==="ALL"||p.complianceStatus===filters.status)&&(p.productName||"").toLowerCase().includes(filters.productName.toLowerCase())&&(p.brandName||"").toLowerCase().includes(filters.brand.toLowerCase())&&shop.toLowerCase().includes(filters.shop.toLowerCase())&&(!filters.unit||(p.unit||"").toLowerCase()===filters.unit.toLowerCase())&&(!filters.minQ||q>=+filters.minQ)&&(!filters.maxQ||q<=+filters.maxQ)&&(!filters.minMrp||p.mrp>=+filters.minMrp)&&(!filters.maxMrp||p.mrp<=+filters.maxMrp)&&(!filters.dateFrom||dt>=new Date(filters.dateFrom+"T00:00:00"))&&(!filters.dateTo||dt<=new Date(filters.dateTo+"T23:59:59.999"))});
 const all=products.length&&products.every(p=>selected.includes(p.id));
 const setF=(k,v)=>{setFilters(x=>({...x,[k]:v}));setSelected([])};
 async function addChild(){if(!childName.trim()||!canAddChild)return;const globalChild=!!canManageGlobal;const endpoint=globalChild?`${API_URL}/categories/global`:`${API_URL}/categories`;const r=await apiFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:childName,parentId:category.id,isFinal:childFinal,sourceType:category.sourceType})});const d=await r.json().catch(()=>null);if(!r.ok)return setMessage(d?.error||"Could not add category");setChildName("");setChildFinal(false);setShowChild(false);setMessage(globalChild?"Global subcategory added for all users.":"Private subcategory added to this account.");load()}
 async function delCategory(id){if(!confirm("Delete this category branch? Registered products will be moved to the appropriate Uncategorized category."))return;const r=await apiFetch(`${API_URL}/categories/${id}`,{method:"DELETE"});const d=await r.json().catch(()=>null);if(!r.ok)return setMessage(d?.error||"Delete failed");location.href=globalManagement?`/admin/categories/${String(category.sourceType||"OFFLINE").toLowerCase()}`:category.parent?`/products/category/${category.parent.id}`:"/products"}
 async function delProducts(){if(!selected.length||deleting||!confirm(`Delete ${selected.length} product(s)?`))return;setDeleting(true);const ids=[...selected];const results=await Promise.allSettled(ids.map(id=>apiFetch(`${API_URL}/products/${id}`,{method:"DELETE"})));const failed=results.filter(result=>result.status==="rejected"||!result.value?.ok).length;setMessage(failed?`${failed} product(s) could not be deleted.`:"Selected products deleted successfully.");setSelected([]);await load();setDeleting(false)}
 if(!category)return <div className="products-page"><p>{message||"Loading..."}</p></div>;
 return <div className="products-page"><Link className="back-link" to={globalManagement?`/admin/categories/${String(category.sourceType||"OFFLINE").toLowerCase()}`:category.parent?`/products/category/${category.parent.id}`:"/products"}>← {globalManagement?"Global categories":"Back"}</Link><div className="page-header"><p className="eyebrow">{globalManagement?"ADMIN · GLOBAL":"PRODUCT DATABASE"} · LEVEL {depth}</p><h1 data-no-auto-translate="true" className="category-identity">{category.name}</h1><p data-no-auto-translate="true" className="category-identity">{pathOf(category)}</p><p>{category.isSystem?"GLOBAL":"PRIVATE"} · {category.sourceType==="ECOMMERCE"?"E-COMMERCE":"OFFLINE"} · {isFinal?"FINAL PRODUCT CATEGORY":"SUBCATEGORY"}</p></div>{message&&<div className="status-message">{message}</div>}
 {(canAddChild||!category.isSystem)&&<section className="product-actions category-toolbar">{canAddChild&&<button className="secondary-action" onClick={()=>setShowChild(v=>!v)}>{canManageGlobal?"+ Add global subcategory":"+ Add private subcategory"}</button>}{(!category.isSystem||canManageGlobal)&&<button className="delete-category-button" onClick={()=>delCategory(category.id)}>{canManageGlobal?"Delete global category":"Delete private category"}</button>}</section>}
 {showChild&&<div className="category-form"><input placeholder={canManageGlobal?"New global subcategory":"New private subcategory"} value={childName} onChange={e=>setChildName(e.target.value)}/><label><input type="checkbox" checked={childFinal} onChange={e=>setChildFinal(e.target.checked)}/> Set as final product type</label><button onClick={addChild}>Add</button><span className="gesture-hint">{canManageGlobal?"Global category · available to all users":"Private category · available only to this account"}</span></div>}
 {!isFinal&&<section className="product-categories"><div className="section-heading"><div><h2>Subcategories</h2><p>{globalManagement?"Create global subcategories here. Private categories are managed separately in Products.":"Global categories can be viewed here. Subcategories you add are private to your account."} Maximum depth is four.</p></div></div><div className="category-grid">{children.map(c=><div className="category-item" key={c.id}><Link className="category-card" to={globalManagement&&c.isSystem?`/admin/categories/${String(c.sourceType||category.sourceType||"OFFLINE").toLowerCase()}/${c.id}?globalAdmin=1`:`/products/category/${c.id}`}><h3 data-no-auto-translate="true" className="category-identity">{c.name}</h3><p>{c.isSystem?"Global":"Private to your account"} · {c.sourceType==="ECOMMERCE"?"E-commerce":"Offline"} · {c.isFinalProductType?"Final category":`Level ${depth+1}`}</p></Link>{(!c.isSystem||canManageGlobal)&&<button className="delete-category-button" onClick={()=>delCategory(c.id)}>Delete</button>}</div>)}</div>{!children.length&&<p>No subcategories yet.</p>}</section>}
 {isFinal&&<section className="product-categories"><div className="section-heading"><div><h2>Registered category products</h2><p>{products.length} products match the current filters.</p></div></div><div className="filter-panel"><input placeholder="Product" value={filters.productName} onChange={e=>setF("productName",e.target.value)}/><input placeholder="Brand" value={filters.brand} onChange={e=>setF("brand",e.target.value)}/><input placeholder="Shop" value={filters.shop} onChange={e=>setF("shop",e.target.value)}/><select value={filters.status} onChange={e=>setF("status",e.target.value)}><option>ALL</option><option>OKAY</option><option>VIOLATION</option><option>NEEDS_REVIEW</option></select><select value={filters.unit} onChange={e=>setF("unit",e.target.value)}><option value="">Any unit</option><option value="mg">mg</option><option value="g">g</option><option value="kg">kg</option><option value="ml">ml</option><option value="L">L</option><option value="pcs">pcs</option><option value="dozen">dozen</option><option value="m">m</option></select><input type="number" placeholder="Min quantity" value={filters.minQ} onChange={e=>setF("minQ",e.target.value)}/><input type="number" placeholder="Max quantity" value={filters.maxQ} onChange={e=>setF("maxQ",e.target.value)}/><input type="number" placeholder="Min MRP" value={filters.minMrp} onChange={e=>setF("minMrp",e.target.value)}/><input type="number" placeholder="Max MRP" value={filters.maxMrp} onChange={e=>setF("maxMrp",e.target.value)}/><label className="filter-date"><span>From date</span><input type="date" value={filters.dateFrom} onChange={e=>setF("dateFrom",e.target.value)}/></label><label className="filter-date"><span>To date</span><input type="date" value={filters.dateTo} onChange={e=>setF("dateTo",e.target.value)}/></label></div><div className="bulk-toolbar"><span className="gesture-hint">Selection controls available to product owner</span>{advancedSelect&&<label><input type="checkbox" checked={!!all} onChange={()=>setSelected(all?[]:products.map(p=>p.id))}/> Select all matching</label>}{advancedSelect&&selected.length>0&&<button className="delete-category-button" disabled={deleting} onClick={delProducts}>{deleting?"Deleting...":`Delete selected (${selected.length})`}</button>}</div><div className="product-list">{products.map(p=><div className="product-row" key={p.id}>{advancedSelect&&<input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])}/>}<Link to={`/products/item/${p.id}`} state={{ product: p }}><div><strong data-no-auto-translate="true" className="product-identity">{p.productName}</strong><span>{p.brandName||"Brand not recorded"}</span></div><div><span>{p.netQuantity||"-"} {p.unit||""}</span><span>₹{p.mrp??"-"} · {p.inspections?.[0]?.shop?.name||"Shop not recorded"}</span></div><span className={`compliance-badge ${p.complianceStatus.toLowerCase()}`}>{p.complianceStatus}</span></Link></div>)}</div></section>}
 </div>;
}
