import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { apiFetch } from "../lib/auth";
import "../styles/ecommerce.css";

const API_URL = "http://localhost:5000/api";
const MAX_IMAGES = 6;
const EDITABLE_FIELDS = [["productName", "Product name"], ["brand", "Brand / Manufacturer"], ["description", "Description"], ["netQuantity", "Net quantity"], ["unit", "Unit"], ["mrp", "MRP / Price"], ["sku", "SKU / MPN"], ["gtin", "GTIN / Barcode"], ["countryOfOrigin", "Country of origin"]];
function flatten(nodes, path = []) { return nodes.flatMap((node) => { const next = [...path, node]; return [{ ...node, path: next }, ...flatten(node.children || [], next)]; }); }
function displayFindingStatus(finding) { return String(finding?.status || "").toUpperCase(); }
function firstMatch(text, patterns) { for (const pattern of patterns) { const match = text.match(pattern); if (match?.[1]) return match[1].trim(); } return ""; }
function parseWrittenListingText(text) {
  const source = String(text || "").replace(/\s+/g, " ").trim();
  if (!source) return {};
  const quantity = firstMatch(source, [/(?:net\s+(?:quantity|content)|net\s+wt\.?|item\s+(?:weight|quantity)|weight)\s*[:\-]?\s*([0-9]+(?:\.[0-9]+)?\s*(?:kg|g|gram|grams|mg|ml|l|litre|liter|litres|liters|pcs?|pieces?))\b/i, /\b([0-9]+(?:\.[0-9]+)?\s*(?:kg|g|mg|ml|l|litre|liter))\b/i]);
  const mrp = firstMatch(source, [/(?:maximum\s+retail\s+price|m\.r\.p\.?|mrp)\s*[:\-]?\s*(?:₹|rs\.?|inr)?\s*([0-9]+(?:\.[0-9]{1,2})?)/i]);
  const brand = firstMatch(source, [/(?:brand|brand\s+name)\s*[:\-]\s*([^|;,]{2,80})/i]);
  const manufacturer = firstMatch(source, [/(?:manufacturer|manufactured\s+by)\s*[:\-]\s*([^|;]{3,160})/i]);
  const origin = firstMatch(source, [/(?:country\s+of\s+origin|country\s+of\s+manufacture)\s*[:\-]\s*([A-Za-z][A-Za-z .'-]{2,50})/i]);
  const barcode = firstMatch(source, [/(?:barcode|ean|gtin)\s*[:\-]?\s*([0-9]{8,14})\b/i]);
  const normalizedQuantity = quantity || "";
  const unit = normalizedQuantity ? (normalizedQuantity.match(/[a-z]+$/i)?.[0] || "") : "";
  return { netQuantity: normalizedQuantity, unit, mrp, brand, manufacturer, countryOfOrigin: origin, gtin: barcode, listingText: source };
}

export default function EcommerceInspection() {
  const navigate = useNavigate();
  const [url, setUrl] = useState(""); const [listing, setListing] = useState(null); const [ocr, setOcr] = useState(null); const [compliance, setCompliance] = useState(null); const [categories, setCategories] = useState([]); const [categoryId, setCategoryId] = useState(""); const [selectedViolations, setSelectedViolations] = useState([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { apiFetch(`${API_URL}/categories/tree/all?sourceType=ECOMMERCE`).then(async (r) => { const d = await r.json().catch(() => []); if (!r.ok) throw new Error(d?.error || "Could not load e-commerce categories"); setCategories(Array.isArray(d) ? d : []); }).catch((e) => setError(e.message)); }, []);
  const imageUrls = (listing?.imageUrls || []).slice(0, MAX_IMAGES); const findings = useMemo(() => compliance?.findings || [], [compliance]); const violationFindings = useMemo(() => findings.filter((f) => displayFindingStatus(f) === "VIOLATION"), [findings]); const allViolationsSelected = violationFindings.length > 0 && violationFindings.every((f) => selectedViolations.includes(String(f.findingId))); const finalCategories = useMemo(() => flatten(categories).filter((c) => c.isFinalProductType && c.sourceType === "ECOMMERCE"), [categories]);
  function setSelectedDefaults(result) { setSelectedViolations((result?.findings || []).filter((f) => displayFindingStatus(f) === "VIOLATION").map((f) => String(f.findingId))); }
  async function inspectListing(event) { event.preventDefault(); const value = url.trim(); if (!/^https?:\/\/\S+$/i.test(value)) return setError("Enter a valid public product listing URL."); setBusy(true); setError(""); setMessage("Fetching the public listing text, structured product data and images..."); setListing(null); setOcr(null); setCompliance(null); setCategoryId(""); setSelectedViolations([]); try { const response = await apiFetch(`${API_URL}/products/ecommerce/analyze-url`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: value }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not inspect the listing."); const written = parseWrittenListingText(data.listing?.text); const mergedListing = { ...(data.listing || {}), ...Object.fromEntries(Object.entries(written).filter(([key, value]) => key !== "listingText" && value && !data.listing?.[key])), listingText: written.listingText || data.listing?.text || "" }; setListing(mergedListing); setOcr(data.ocr || null); setCompliance(data.compliance || null); setSelectedDefaults(data.compliance); setMessage("Listing company text and image OCR were collected. Written listing data is used for inspection, with images retained as supporting evidence."); if (Object.values(written).some(Boolean)) { setTimeout(async () => { try { const overrides = Object.fromEntries(EDITABLE_FIELDS.map(([key]) => [key, mergedListing[key] ?? ""])); const check = await apiFetch(`${API_URL}/products/ecommerce/evaluate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listing: mergedListing, ocr: data.ocr || null, overrides }) }); const checked = await check.json().catch(() => ({})); if (check.ok) { setListing(checked.listing || mergedListing); setCompliance(checked.compliance || null); setSelectedDefaults(checked.compliance); setMessage("Written listing data was merged with image OCR and the combined data was checked by the Rules Engine."); } } catch {} }, 0); } } catch (e) { setError(e.message || "E-commerce inspection failed."); } finally { setBusy(false); } }
  function updateListing(key, value) { setListing((current) => ({ ...current, [key]: value })); }
  async function reevaluate() { if (!listing?.url) return; setBusy(true); setError(""); try { const overrides = Object.fromEntries(EDITABLE_FIELDS.map(([key]) => [key, listing[key] ?? ""])); const response = await apiFetch(`${API_URL}/products/ecommerce/evaluate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ listing, ocr, overrides }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not re-run the Rules Engine."); setListing(data.listing || listing); setCompliance(data.compliance || null); setSelectedDefaults(data.compliance); setMessage("Edited written listing data was re-checked with the image OCR evidence."); } catch (e) { setError(e.message || "Rules Engine re-check failed."); } finally { setBusy(false); } }
  function toggleViolation(id) { const key = String(id); setSelectedViolations((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]); }
  function toggleAllViolations() { setSelectedViolations(allViolationsSelected ? [] : violationFindings.map((f) => String(f.findingId))); }
  async function saveProduct() { if (!listing?.url) return; if (!categoryId) return setError("Select an e-commerce final product category before saving."); if (!listing.productName?.trim()) return setError("Product name is required."); setSaving(true); setError(""); setMessage("Saving the reviewed e-commerce product..."); try { const selected = finalCategories.find((c) => c.id === categoryId); const website = listing.websiteName || new URL(listing.url).hostname.replace(/^www\./i, ""); const payload = { categoryId, brandName: listing.brand || "", productName: listing.productName, description: listing.description || "", netQuantity: listing.netQuantity || "", unit: listing.unit || "", mrp: listing.mrp || "", barcode: listing.gtin || "", imageUrls, ocrData: { provider: "ecommerce_public_listing", ocr, compliance, listing, writtenListingText: listing.listingText || listing.text || "", complianceReview: { selectedViolationIds: selectedViolations } }, acceptedFindingIds: selectedViolations, shopName: website, shopAddress: "", shopCity: "", shopState: "", notes: `E-commerce listing reviewed from ${listing.url}. Final category: ${selected?.path?.map((x) => x.name).join(" → ") || ""}`, sourceType: "ECOMMERCE", sourceUrl: listing.url, sourceWebsiteName: website }; const response = await apiFetch(`${API_URL}/products`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not save e-commerce product."); const productId = data.product?.id || data.id; if (!productId) throw new Error("Product was saved but no product ID was returned."); navigate(`/ecommerce-products`); } catch (e) { setError(e.message || "Could not save e-commerce product."); } finally { setSaving(false); } }
  return <div className="ecommerce-page"><div className="page-header"><p className="eyebrow">E-COMMERCE INSPECTION</p><h1>Inspect Product Listing</h1><p>Enter a public listing URL. PARAKH uses the listing company's written product information as the primary source, then cross-checks it against retrieved product images and image OCR.</p><p><Link to="/ecommerce-products">View saved e-commerce products →</Link></p></div>
    <form className="ecommerce-panel ecommerce-url-form" onSubmit={inspectListing}><label className="ecommerce-url-field"><span>Product listing URL</span><input className="ecommerce-url-input" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com/product/..." disabled={busy || saving} /></label><button className="primary-button ecommerce-inspect-button" type="submit" disabled={busy || saving}>{busy ? "Inspecting listing..." : "Inspect Listing"}</button><small>Use public pages and sources that permit automated retrieval. Protected pages, private URLs and login-only content are not accessed.</small></form>
    {error && <div className="status-message">{error}</div>}{message && !error && <div className="status-message">{message}</div>}
    {listing && <section className="ecommerce-panel"><div className="section-heading"><div><h2>Listing Data</h2><p>{listing.sourceTitle || listing.title || "Public product listing"} · <a href={listing.url} target="_blank" rel="noreferrer">Open source page</a></p></div></div><div className="ecommerce-edit-grid">{EDITABLE_FIELDS.map(([key, label]) => <label key={key} className={key === "description" ? "full-width" : ""}><span>{label}</span>{key === "description" ? <textarea value={listing[key] || ""} onChange={(e) => updateListing(key, e.target.value)} /> : <input value={listing[key] || ""} onChange={(e) => updateListing(key, e.target.value)} />}</label>)}<label><span>Website</span><input value={listing.websiteName || ""} readOnly /></label><label><span>Country-of-origin filter evidence</span><select value={listing.filterEvidence ? "true" : "false"} onChange={(e) => updateListing("filterEvidence", e.target.value === "true")}><option value="true">Detected on listing page</option><option value="false">Not established</option></select></label><label className="full-width"><span>E-commerce final product category *</span><select value={categoryId} onChange={(e) => setCategoryId(e.target.value)}><option value="">Select e-commerce final category</option>{finalCategories.map((c) => <option key={c.id} value={c.id}>{c.path.map((x) => x.name).join(" → ")}</option>)}</select></label></div><div className="ecommerce-edit-actions"><button type="button" className="secondary-action" onClick={reevaluate} disabled={busy || saving}>Re-run Rules Engine</button><button type="button" className="primary-button" onClick={saveProduct} disabled={saving || busy}>{saving ? "Saving..." : "Save E-commerce Product"}</button></div></section>}
    {imageUrls.length > 0 && <section className="ecommerce-panel"><div className="section-heading"><div><h2>Listing Images Retrieved</h2><p>Images are retained as supporting package evidence and cross-checked with the written listing data.</p></div></div><div className="ecommerce-images">{imageUrls.map((imageUrl, index) => <div className="ecommerce-image" key={imageUrl}><img src={imageUrl} alt={`Listing product ${index + 1}`} /><span>Image {index + 1}</span></div>)}</div></section>}
    {ocr && <section className="ecommerce-panel"><div className="section-heading"><div><h2>Image OCR Cross-check</h2><p>OCR is secondary evidence used to compare the package images with the listing company's written information.</p></div></div><div className="ecommerce-fields">{["productName", "brandName", "countryOfOrigin", "mrp", "netQuantity", "unit", "manufacturer"].map((key) => <div key={key}><strong>{key.replace(/([A-Z])/g, " $1")}</strong><span>{ocr?.[key]?.value || "Not established"}</span></div>)}</div></section>}
    {compliance && <section className="ecommerce-panel"><div className="section-heading"><div><h2>Rules Engine Result</h2><p>E-commerce listing context. Findings use the written listing information plus image evidence and remain inspection support information.</p></div></div><div className="ecommerce-result-summary"><div><span>Status</span><strong>{compliance.overallStatus || "REVIEW"}</strong></div><div><span>Violations selected</span><strong>{selectedViolations.length}</strong></div><div><span>Unable to verify</span><strong>{compliance.summary?.unableToVerify ?? 0}</strong></div></div>{violationFindings.length > 0 && <div className="ecommerce-selection-bar"><button type="button" className="violation-select-button" onClick={toggleAllViolations}>{allViolationsSelected ? "Deselect all violations" : "Select all violations"}</button><span>{selectedViolations.length} of {violationFindings.length} violations selected</span></div>}<div className="ecommerce-findings">{findings.map((finding, index) => { const isViolation = displayFindingStatus(finding) === "VIOLATION"; const selectedFinding = selectedViolations.includes(String(finding.findingId)); return <article className={`${isViolation ? "ecommerce-finding-row violation" : "ecommerce-finding-row"} ${selectedFinding ? "selected" : ""}`} key={finding.findingId || index}>{isViolation && <button type="button" className={`violation-row-toggle ${selectedFinding ? "selected" : ""}`} onClick={() => toggleViolation(finding.findingId)} aria-pressed={selectedFinding}>{selectedFinding ? "Selected" : "Select"}</button>}<div><strong>{finding.ruleNumber || finding.ruleCode || "Rule"}</strong><span>{finding.message}</span>{finding.violationReason && <small>{finding.violationReason}</small>}</div></article>; })}</div></section>}
  </div>;
}
