import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/auth";
import "../styles/history.css";
const API_URL = "http://localhost:5000/api";
function History() {
  const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const [brand, setBrand] = useState(""); const [shop, setShop] = useState(""); const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState("");
  useEffect(() => { let alive = true; apiFetch(`${API_URL}/products/history`).then(async (r) => { const d = await r.json(); if (!r.ok) throw new Error(d.error || "Failed to load history"); if (alive) setProducts(Array.isArray(d) ? d : []); }).catch((e) => alive && setError(e.message)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  const shown = useMemo(() => products.filter((p) => { const inspection = p.inspections?.[0]; const haystack = `${p.productName || ""} ${p.brandName || ""} ${p.category?.name || ""} ${inspection?.shop?.name || ""} ${p.barcode || ""}`.toLowerCase(); return (!query.trim() || haystack.includes(query.trim().toLowerCase())) && (status === "ALL" || p.complianceStatus === status) && (!brand.trim() || (p.brandName || "").toLowerCase().includes(brand.trim().toLowerCase())) && (!shop.trim() || (inspection?.shop?.name || "").toLowerCase().includes(shop.trim().toLowerCase())) && (!dateFrom || new Date(inspection?.inspectedAt || p.createdAt) >= new Date(dateFrom + "T00:00:00")) && (!dateTo || new Date(inspection?.inspectedAt || p.createdAt) <= new Date(dateTo + "T23:59:59.999"))); }), [products, query, status, brand, shop, dateFrom, dateTo]);
  function clear() { setQuery(""); setStatus("ALL"); setBrand(""); setShop(""); setDateFrom(""); setDateTo(""); }
  return <div className="history-page"><div className="page-header"><p className="eyebrow">INSPECTION RECORDS</p><h1>Inspection History</h1><p>Saved registrations and inspections belong to the signed-in user.</p></div><div className="history-toolbar history-toolbar-wide"><label className="history-search"><span>Search</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Product, category, shop or barcode" /></label><label className="history-filter"><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="OKAY">Okay</option><option value="VIOLATION">Violation</option><option value="NEEDS_REVIEW">Needs review</option></select></label><label className="history-search"><span>Brand</span><input value={brand} onChange={(e) => setBrand(e.target.value)} placeholder="Any brand" /></label><label className="history-search"><span>Shop</span><input value={shop} onChange={(e) => setShop(e.target.value)} placeholder="Any shop" /></label><label className="history-filter"><span>From date</span><input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} /></label><label className="history-filter"><span>To date</span><input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} /></label><button className="history-clear" type="button" onClick={clear}>Clear</button></div>{loading && <p className="history-loading">Loading inspection history...</p>}{error && <div className="status-message">{error}</div>}{!loading && !error && !shown.length && <div className="status-message">No inspections match the current filters.</div>}{!loading && !error && shown.length > 0 && <div className="history-list">{shown.map((p) => { const s = p.complianceStatus || "NEEDS_REVIEW"; const inspection = p.inspections?.[0]; return <Link key={p.id} to={`/products/item/${p.id}`} className="history-item"><div><h3>{p.productName}</h3><p>{p.brandName || "Company not recorded"} · {p.category?.name || "Uncategorised"} · {inspection?.shop?.name || "Shop not recorded"}</p><small>{new Date(inspection?.inspectedAt || p.createdAt).toLocaleString()}</small></div><span className={`history-status ${s === "OKAY" ? "compliant" : s === "VIOLATION" ? "non-compliant" : "review"}`}>{s}</span></Link>; })}</div>}</div>;
}
export default History;
