import { useEffect, useState } from "react";
import { apiFetch, getUser } from "../lib/auth";
import { downloadTextPdf } from "../lib/pdf";
import "../styles/reports.css";

const API_URL = "http://localhost:5000/api";
function Reports() {
  const [products, setProducts] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const user = getUser();
  useEffect(() => { const timer = window.setTimeout(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams(); if (query.trim()) params.set("query", query.trim()); if (status !== "ALL") params.set("status", status); const r = await apiFetch(`${API_URL}/products/history${params.toString() ? `?${params}` : ""}`); const data = await r.json(); if (!r.ok) throw new Error(data.error || "Could not load reports"); setProducts(Array.isArray(data) ? data : []); } catch (e) { setError(e.message); setProducts([]); } finally { setLoading(false); } }, 300); return () => window.clearTimeout(timer); }, [query, status]);
  async function downloadReport(p) { try { const r = await apiFetch(`${API_URL}/products/${p.id}`); const full = await r.json(); if (!r.ok) throw new Error(full.error || "Could not load product report"); const shop = full.inspections?.[0]?.shop; const inspector = full.inspections?.[0]?.worker?.name || full.owner?.name || user?.name || "Not recorded"; const path = [full.category?.parent?.parent?.parent, full.category?.parent?.parent, full.category?.parent, full.category].filter(Boolean).map((x) => x.name).join(" > "); let stored = null; try { stored = full.ocrData ? JSON.parse(full.ocrData) : null; } catch {} const violations = Array.isArray(stored?.compliance?.findings) ? stored.compliance.findings.filter((f) => String(f?.status || "").toUpperCase() === "VIOLATION") : []; downloadTextPdf(`PARAKH-${String(full.productName || "product").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "")}.pdf`, [
      { title: "Product Details", rows: [
        { label: "Product", value: full.productName }, { label: "Brand / Manufacturer", value: full.brandName || "Not recorded" }, { label: "Category", value: path || full.category?.name || "Not recorded" }, { label: "MRP", value: full.mrp == null ? "Not recorded" : `Rs. ${full.mrp}` }, { label: "Net Quantity", value: `${full.netQuantity || "Not recorded"} ${full.unit || ""}` }, { label: "Barcode", value: full.barcode || "Not recorded" }, { label: "Shop", value: shop?.name || "Not recorded" }, { label: "Inspection Date", value: new Date(full.inspections?.[0]?.inspectedAt || full.createdAt).toLocaleString() },
      ] },
      { title: "User / Inspector Details", rows: [
        { label: "Name", value: inspector }, { label: "Email", value: full.owner?.email || user?.email || "Not recorded" }, { label: "Role", value: user?.role || "USER" }, { label: "Compliance Status", value: full.complianceStatus || "NEEDS_REVIEW" },
      ] },
      { title: "Rules Violated by This Product", rows: violations.length ? violations.map((f) => ({ label: f.ruleNumber || "Rule", value: [f.message, f.violationReason].filter(Boolean).join(" | ") || "Violation recorded" })) : [{ label: "Result", value: "No Rules Engine violations were recorded for this product." }] },
    ]); } catch (e) { setError(e.message || "Could not generate the report"); } }
  return <div className="reports-page"><div className="page-header"><p className="eyebrow">REPORTS</p><h1>Inspection Reports</h1><p>Search an inspection and download a product-specific PDF containing product details, inspector details and only its recorded Rules Engine violations.</p></div><div className="reports-toolbar"><label className="reports-search"><span>Search</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Product, brand, category, shop or barcode..." /></label><label className="reports-filter"><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="OKAY">Okay</option><option value="VIOLATION">Violation</option><option value="NEEDS_REVIEW">Needs review</option></select></label><button className="reports-clear" type="button" onClick={() => { setQuery(""); setStatus("ALL"); }}>Clear</button></div>{loading && <p className="reports-loading">Loading reports...</p>}{error && <div className="status-message">{error}</div>}{!loading && !error && !products.length && <div className="status-message">No reports match the current search and filter.</div>}{!loading && !error && products.map((p) => <div className="report-card" key={p.id}><div><h3>{p.productName}</h3><p>{p.brandName || "Brand not recorded"} · {p.category?.name || "Uncategorised"} · {p.inspections?.[0]?.shop?.name || "No shop"}</p><div className="report-meta"><span>MRP Rs. {p.mrp ?? "-"}</span><span>{p.netQuantity || "-"} {p.unit || ""}</span><span>{p.complianceStatus}</span><span>{p.owner?.name || user?.name || "User"}</span></div></div><button className="report-button" type="button" onClick={() => downloadReport(p)}>Download PDF</button></div>)}</div>;
}
export default Reports;
